### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by bochaco**
I'm offering myself to create the first draft of the Spanish version for this book.

### CODE REVIEW

**Comment by bochaco** [comment]
Please note I'm new to github/gitbook so forgive me if I'm not following the process correctly.

**Comment by Viv-Rajkumar** [comment]
Heya,

Cheers for submitting a translation. Can you please group all your changes for a language into a single PR than multiple patches please. You can continue to work in your fork until it's complete and submit the entire changeset as a single PR.

We can't accept PR's with partial changes to master as it's the branch the live gitbook is currently based on.

**Comment by bochaco** [comment]
Hi,

Sure!, I'll try to do that, I'm missing the translation of one file so I'll try to create a single PR for all of them when I finish with it.

Cheers,
Gabriel

**Comment by Viv-Rajkumar** [comment]
@bochaco Perfect. That'd be ideal :). I'll close these PR's for now and will use the new PR when submitted. Thanks again for your help with translations.

**Comment by ma7as** [comment]
Hola Grabriel, también estoy probando esto para colaborar con la traducción, te paso mi correo colonizare@yahoo.com.ar

**Pull request closed without merging**
